### ISSUE TITLE
Qt 5.7 Support

### ISSUE THREAD

**Issue by ubuntuvibes** [adgellida/ubunsys#1]
Hello,

The deb package requires minimum Qt version to be 5.8. Can't it be built using Qt 5.7?

Latest Ubuntu 17.04 ships with Qt 5.7.1 and this app can't be used on it.

**Comment by adgellida** [comment]
I am very pleased for your interest about this app!

Now designed for 16.10 and 5.8.0.

Temporal solution:

There's a way to point your system to your 5.8 installed outside official repositories.

1. Download 5.8.0:

http://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-linux-x64-5.8.0.run

2. Install ubunsys from deb.

3. Run ubunsys:

`LD_LIBRARY_PATH=/home/$USER/.Qt5.8.0/5.8/gcc_64/lib /usr/bin/ubunsys`

If you can run it, sweet!! Nowadays this week I'll compile it for 5.7.1 as you desire and thinking in developing for 17.04.

**Comment by adgellida** [comment]
Check if solved here: https://github.com/adgellida/ubunsys/releases/download/v2017.05.08/ubunsys_2017.05.08_all.deb

From now 5.7.1 and 17.04.
