### ISSUE TITLE
Exclusively use visudo to edit file /etc/sudoers

### ISSUE THREAD

**Issue by Dodobeard** [adgellida/ubunsys#12]
Menu item 'Tweaks > Security > sudoers > Edit' open config file /etc/sudoers in a plain text editor.

There's a number of reasons why you don't want to do that. Use /usr/sbin/visudo instead. Unlike a plain text editor, visudo does basic sanity and syntax checking and won't save a corrupted sudoers-file, locking users without root access out of the privileged group of users.

Please fix.
![sudoers](https://user-images.githubusercontent.com/32935096/31779005-68bc2804-b4f2-11e7-80f3-ca59ba91d2ba.png)

**Comment by adgellida** [comment]
Solved, thanks for help brother!
