### ISSUE TITLE
apt-fast is broken

### ISSUE THREAD

**Issue by Dodobeard** [adgellida/ubunsys#13]
Ubunsys relies on apt-fast which is currently broken due to a bug in its install script.
See: https://github.com/ilikenwf/apt-fast/issues/132

If apt-fast isn't already installed, running Ubunsys will fail because of this broken package from another PPA.

**Comment by adgellida** [comment]
I know... will be fixed.

**Comment by adgellida** [comment]
Possible temporal solution, install apt-fast from here, is solved?

https://github.com/adgellida/ubunsys/releases/download/v2017.10.02/apt-fast_1.8.3.144.git3a6bd77-0ubuntu1.ppa4_all_MODIFIED.deb

**Comment by adgellida** [comment]
When you open ubunsys and apt-fast is not installed or not correctly installed a patched version is installed. When official package maintainer upload a new release with this solved I'll modify this, installing the latest official version.
