### ISSUE TITLE
32bits package or recompiling...

### ISSUE THREAD

**Issue by C138** [adgellida/ubunsys#14]
Hi
Would be nice to have a 32bits compatible package...
Tried to recompile but nothing is said about the way to do ...

Ok, wget ubunsys-source... ... / 
Ok, debian/ src/ are there, seems good
but  what's next... ? 

Can find any usual command like "fakeroot debian/rules ...."  that gives something..

Thanks
Ps : Ok, manual compilation works, but I would like to rebuild the package...

**Comment by adgellida** [comment]
I'll study this.

**Comment by adgellida** [comment]
Solution ASAP. Maybe the weekend.

**Comment by adgellida** [comment]
For now i386 not working on my tests... I'm on it.

**Comment by adgellida** [comment]
Test i386 deb package on last release and say to me, not PPA yet.

**Comment by adgellida** [comment]
I close this issue, for now no i386 compatibility on future releases.
