### ISSUE TITLE
PPA for Ubuntu 18.10 Cosmic Cuttlefish

### ISSUE THREAD

**Issue by AdamKane41** [adgellida/ubunsys#15]
Can we have an updated PPA on [launchpad](https://launchpad.net/~adgellida/+archive/ubuntu/ubunsys) for Ubuntu 18.10 Cosmic Cuttlefish?
...Pretty please.. thanks! ;-)

**Comment by adgellida** [comment]
Of course. Updated. But ubunsys is installable in all ubuntu versions through:

- `wget https://raw.githubusercontent.com/adgellida/ubuntupackages/master/apps1/ubunsys && sudo chmod 777 ubunsys && sudo ./ubunsys`

- deb package
