### ISSUE TITLE
ubuntu 16.04 support

### ISSUE THREAD

**Issue by milad0123** [adgellida/ubunsys#3]
hi.
please add ubuntu 16.04 package.
and enabling this functions would be great:
show hidden startup items:
`sudo sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop`
and disabling login sound with remove or rename this file:
/usr/share/sounds/ubuntu/stereo/system-ready.ogg

thanks bro.

**Comment by adgellida** [comment]
I'll keep that in mind. When it's done, I'll let you know.

**Comment by adgellida** [comment]
Test if ok and say to me bugs.
